config/routes.rb
Rails.application.routes.draw do
  get 'wishlist_product/show'
  get 'wishlist/show'
  resources :carts
  resources :credit_cards
  resources :orders
  resources :billing_addresses
  resources :shipping_addresses
  resources :products
  resources :categories

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#new'

  get "sign_up", to: "users#new"
  get 'log_out', to: 'extra#new'
  get 'accounts', to: 'users#index', as: "users"
  get 'my_account', to: 'users#show'
  get 'products_by_category', to: 'products_by_category#new'
  get 'my_cart', to: 'carts#show'
  get 'wishlist', to: 'wishlist_product#show'
  get 'export_csv_orders', to: 'orders#export_csv'
  post 'carts/add'
  post 'carts/remove'
  post 'carts/update_quantity'
  post 'wishlist_product/add'
  post 'wishlist_product/remove'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/billing_address.rb
class BillingAddress < ApplicationRecord
    belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :orderables
    has_many :products, through: :orderables

    def total
        orderables.to_a.sum { |orderable| orderable.total }
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :ordered_products
    has_many :products, through: :ordered_products

    def total
        ordered_products.to_a.sum { |product| product.total }
    end
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category 
    has_one_attached :image
    has_many :orderables
    has_many :carts, through: :orderables
    has_many :ordered_products
    has_many :wishlist_products
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :shipping_address
  has_one :billing_address
  has_one :credit_card
  has_one :cart
  has_one_attached :profile_picture
  has_many :orders
  has_many :wishlist_products

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def admin?
    self.role == "admin"
  end

end

app/models/wishlist_product.rb
class WishlistProduct < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def new
        @products = Product.all.with_attached_image.order(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand me-2">
      <%= image_tag("logo.png", alt: "logo", id: "navbar-image") %>
    </a>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"> <%= link_to "Home", root_path, class: "nav-link", id: "nav-link-text" %></li>
        <% if !(current_user.present? && current_user.admin?) %>
          <li class="nav-item"> <%= link_to "Men", products_by_category_path(:category_name => "Men"), class: "nav-link", id: "nav-link-text" %></li>
          <li class="nav-item"> <%= link_to "Women", products_by_category_path(:category_name => "Women"), class: "nav-link", id: "nav-link-text" %></li>
          <li class="nav-item"> <%= link_to "Unisex", products_by_category_path(:category_name => "Unisex"), class: "nav-link", id: "nav-link-text" %></li>
        <% end %>
        <% if current_user.present? %>
          <% if current_user.admin? %>
            <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link", id: "nav-link-text" %></li>
            <li class="nav-item"> <%= link_to "Categories", categories_path, class: "nav-link", id: "nav-link-text" %></li>
            <li class="nav-item"> <%= link_to "Products", products_path, class: "nav-link", id: "nav-link-text" %></li>
            <li class="nav-item"><%= link_to "Orders", orders_path, class: "nav-link", id: "nav-link-text" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "My Orders", orders_path(user_id: current_user.id), class: "nav-link", id: "nav-link-text" %></li>
          <% end %>
          <li class="nav-item"><%= link_to "My Account", my_account_path, class: "nav-link", id: "nav-link-text" %></li>
        <% end %>
        <% if !(current_user.present? && current_user.admin?) %>
          <%= form_tag(products_by_category_path, method: :get) do %>
            <%= text_field_tag(:search, params[:search], :style => "border-top-left-radius: 10px; border-bottom-left-radius: 10px; background-color: #FAFAD2; margin-left: 50px; height: 35px;") %>
            <%= submit_tag 'Search', class: 'gold-button', style: "font-family: 'Dancing Script', cursive; border-top-left-radius: 0px; border-bottom-left-radius: 0px; margin-left: -5px;" %>
          <% end %>
        <% end %>
      </ul>
      <!-- Right links -->
      <div class="d-flex align-items-center justify-content-end">
        <% if !user_signed_in? %>
          <%= link_to "Sign In", user_session_path, method: :post , id: "sign-in-button-text" %>
          <div role="button", class="btn btn-dark me-3", id="nav-button">
            <%= link_to "Sign Up", new_user_registration_path, method: :post , id: "sign-up-button-text" %> 
          </div>
        <% else %>
          <div role="button", class="btn btn-dark me-3", id="nav-button">
            <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete , id: "sign-out-button-text"%> 
          </div>
          <% if !current_user.admin?%>
            <div style="position: relative; margin-right: 10px;">
              <%= link_to image_tag("shopping-bag-gold.png", alt: "cart", id: "cart"), my_cart_path %> 
              <p class="circle"><%= if current_user.cart.present? then current_user.cart.orderables.count else 0 end %></p>
            </div>
            <div style="position: relative;">
              <%= link_to '💛', wishlist_path, style: "text-decoration-color: transparent; font-size: 27px;"%>
              <p class="circle"><%= if current_user.wishlist_products.present? then current_user.wishlist_products.count else 0 end %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->