config/routes.rb
Rails.application.routes.draw do
  get 'wishlist_product/show'
  get 'wishlist/show'
  resources :carts
  resources :credit_cards
  resources :orders
  resources :billing_addresses
  resources :shipping_addresses
  resources :products
  resources :categories

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#new'

  get "sign_up", to: "users#new"
  get 'log_out', to: 'extra#new'
  get 'accounts', to: 'users#index', as: "users"
  get 'my_account', to: 'users#show'
  get 'products_by_category', to: 'products_by_category#new'
  get 'my_cart', to: 'carts#show'
  get 'wishlist', to: 'wishlist_product#show'
  get 'export_csv_orders', to: 'orders#export_csv'
  post 'carts/add'
  post 'carts/remove'
  post 'carts/update_quantity'
  post 'wishlist_product/add'
  post 'wishlist_product/remove'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/billing_address.rb
class BillingAddress < ApplicationRecord
    belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :orderables
    has_many :products, through: :orderables

    def total
        orderables.to_a.sum { |orderable| orderable.total }
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :ordered_products
    has_many :products, through: :ordered_products

    def total
        ordered_products.to_a.sum { |product| product.total }
    end
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category 
    has_one_attached :image
    has_many :orderables
    has_many :carts, through: :orderables
    has_many :ordered_products
    has_many :wishlist_products
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :shipping_address
  has_one :billing_address
  has_one :credit_card
  has_one :cart
  has_one_attached :profile_picture
  has_many :orders
  has_many :wishlist_products

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def admin?
    self.role == "admin"
  end

end

app/models/wishlist_product.rb
class WishlistProduct < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  def add
    @cart = current_user.cart
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_f
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: current_orderable.quantity + 1)
    else 
      @cart.orderables.create(product: @product, quantity: 1)
    end

    if @cart.save
      redirect_to product_url(@product), success: "Product successfully added to cart!"
    else
      redirect_to product_url(@product), danger: "Product couldn't be added to cart! " 
    end
  end

  def update_quantity
    @cart = current_user.cart
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_f
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy
    end

    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to my_cart_path }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to my_cart_path }
      format.json { head :no_content }
    end
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/1/edit
  def edit
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find_or_create_by(user_id: current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/extra_controller.rb
class ExtraController < ApplicationController
    def new
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def new
        @products = Product.all.with_attached_image.order(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin, except: [:show]
  def index
    @users = User.all
  end

  def show
    @user = current_user
    if @user.shipping_address.nil?
      address = ShippingAddress.create(user_id: @user.id)
      address.save
      @user.shipping_address = address
    end

    if @user.billing_address.nil?
      address = BillingAddress.create(user_id: @user.id)
      address.save
      @user.billing_address = address
    end

    if @user.credit_card.nil?
      card = CreditCard.create(user_id: @user.id)
      card.save
      @user.credit_card = card
    end

    @shipping_address = @user.shipping_address
    @billing_address = @user.billing_address
    @credit_card = @user.credit_card
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_orderables.html.erb
<table class="table">
      <thead>
        <tr>
          <th scope="col" style="text-align: left;">Your Order</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Subtotal</th>
        </tr>
      </thead>
      <tbody>
        <% @cart.orderables.each do |orderable| %>
            <% product = orderable.product %>
            <tr>
                <td style="text-align: left;"> 
                    <div class="row">
                        <div class="column" style="float: left; width: 25%;">
                            <%= image_tag(product.image, width: "100", height: "100")%>
                        </div>
                        <div class="column" style="float: left; width: 40%;">
                            <h6 style="font-family: 'Montserrat', sans-serif;"><%= product.brand %></h6>
                            <h4 style="font-family: 'Montserrat', sans-serif; text-shadow: 0.4px 0.4px 0.4px black;"><%= product.name %></h4>
                            <p style="font-family: 'Montserrat', sans-serif;"><%= product.perfumetype %> - <%= product.quantity %> ml</p>
                        </div>
                    </div>
                </td>
                <td><h6 style="font-family: 'Montserrat', sans-serif;">€<%= product.price %></h6></td>
                <td>
                    <%= form_with(url: carts_update_quantity_path) do |f| %>
                        <%= f.hidden_field :id, value: product. id %>
                        <%= f.number_field :quantity, value: orderable.quantity, min: 1, style: "border-radius: 5px; border-color: transparent; outline-style: solid; outline-color: black; outline-width: thin; padding-top:3px; padding-bottom:3px;" %> 
                        <%= f.submit "Update", onclick: my_cart_path, class: "gold-button", style: "font-family: 'Dancing Script', cursive;" %>
                    <% end %>  
                </td>
                <td><h6 style="font-family: 'Montserrat', sans-serif;">€<%= orderable.total %></h6></td>
                <td>
                    <%= form_with(url: carts_remove_path) do |f| %>
                        <%= f.hidden_field :id, value: orderable.id %> 
                        <%= f.submit "X", style: "border-radius: 50%; height:30px; width:30px; background-color: #C09040; font-weight: 800;" %>
                    <% end %>
                </td>
            </tr>
        <% end %> 
    </tbody>
</table>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<div>

  <h1 class="shadow-text" style="margin-top: 35px; margin-bottom: 50px;">
    <%= image_tag('shopping-bag.png', alt: 'cart', id: 'cart', style: "height: 50px; margin-bottom: 10px;") %>
    Shopping cart
  </h1>

  <% if @cart.orderables.present? %>
    <div style="margin-left: 10%; margin-right: 10%;">
        <%= render "orderables" %>
    </div>
    <h1 style="float:right; margin-right: 10%; font-family: 'Lobster', sans-serif;"> Total: €<%= @cart.total %> </h1>
    <br><br><br>
    <%= button_to 'PLACE ORDER', orders_path(order: { user_id: current_user.id }), 
                            data: {turbo_method: :post, turbo_confirm: "Are you sure you want to order?"}, class: "order-button"%>
  <% else %>
    <p style="text-align: center;">
      <%= image_tag('empty-cart-gold.png', alt: 'cart', id: 'cart', style: "height: 500px;") %> 
    </p>
  <% end %>

</div>