config/routes.rb
Rails.application.routes.draw do
  get 'wishlist_product/show'
  get 'wishlist/show'
  resources :carts
  resources :credit_cards
  resources :orders
  resources :billing_addresses
  resources :shipping_addresses
  resources :products
  resources :categories

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#new'

  get "sign_up", to: "users#new"
  get 'log_out', to: 'extra#new'
  get 'accounts', to: 'users#index', as: "users"
  get 'my_account', to: 'users#show'
  get 'products_by_category', to: 'products_by_category#new'
  get 'my_cart', to: 'carts#show'
  get 'wishlist', to: 'wishlist_product#show'
  get 'export_csv_orders', to: 'orders#export_csv'
  post 'carts/add'
  post 'carts/remove'
  post 'carts/update_quantity'
  post 'wishlist_product/add'
  post 'wishlist_product/remove'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/billing_address.rb
class BillingAddress < ApplicationRecord
    belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :orderables
    has_many :products, through: :orderables

    def total
        orderables.to_a.sum { |orderable| orderable.total }
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
    belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :ordered_products
    has_many :products, through: :ordered_products

    def total
        ordered_products.to_a.sum { |product| product.total }
    end
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category 
    has_one_attached :image
    has_many :orderables
    has_many :carts, through: :orderables
    has_many :ordered_products
    has_many :wishlist_products
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :shipping_address
  has_one :billing_address
  has_one :credit_card
  has_one :cart
  has_one_attached :profile_picture
  has_many :orders
  has_many :wishlist_products

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def admin?
    self.role == "admin"
  end

end

app/models/wishlist_product.rb
class WishlistProduct < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  def add
    @cart = current_user.cart
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_f
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: current_orderable.quantity + 1)
    else 
      @cart.orderables.create(product: @product, quantity: 1)
    end

    if @cart.save
      redirect_to product_url(@product), success: "Product successfully added to cart!"
    else
      redirect_to product_url(@product), danger: "Product couldn't be added to cart! " 
    end
  end

  def update_quantity
    @cart = current_user.cart
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_f
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy
    end

    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to my_cart_path }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to my_cart_path }
      format.json { head :no_content }
    end
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/1/edit
  def edit
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find_or_create_by(user_id: current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_admin
  
  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:id, :name, :description)
    end
end

app/controllers/extra_controller.rb
class ExtraController < ApplicationController
    def new
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def new
        @products = Product.all.with_attached_image.order(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <div class="form-outline mb-4">
    <%= f.text_field :name, autofocus: true, required: true, class: "form-control", placeholder: "Name", id: "text-field"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_area :description, autofocus: true, required: true, class: "form-control", placeholder: "Description", id: "text-field"%>
  </div>
  <br>

  <div class="actions">
    <%= f.submit button_text, class: "btn btn-info btn-block mb-4" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="category">

  <h1 class="font-effect-outline" id="new-category-title">Editing category</h1>

  <%= render "form", button_text: "Update" %>

  <br>

  <%= link_to "Back to categories", categories_path, class: "btn btn-warning", id: "back-button" %>
  <%= link_to "Show this category", @category, class: "btn btn-primary", id: "back-button" , style: "float: right;" %> 

</div>

app/views/categories/index.html.erb
<div class="container mt-5">
  <h2 class="gold-title">Categories</h2>
  <br>
  <%= link_to 'New Category', new_category_path, class: "btn btn-info btn-lg btn-block", id: "new-button" %>
  <br>
  <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Products</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td><%= category.description %></td>
            <td><%= link_to "View #{category.product.count} Products", products_path(category_id: category.id), style: "color: black; font-weight: 600;" %></td>
            <td>
              <%= link_to 'Show', category, class: "btn btn-primary btn-sm", style: "margin:2px;" %>  
              <%= link_to 'Edit', edit_category_path(category), class: "btn btn-success btn-sm", style: "margin:2px;" %> 
              <%= link_to 'Destroy', category, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm", style: "margin:2px;" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/categories/new.html.erb
<div class="category">

    <h1 class="font-effect-outline" id="new-category-title">New Category</h1>

    <%= render 'form', button_text: "Create"%>

    <%= link_to 'Back', categories_path, class: "btn btn-warning", id: "back-button" %>

</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div class="card text-center border-info mb-3", style="width: 45rem; margin: auto; margin-top: 10%;">
  <div class="card-header">
    <%= @category.name %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @category.description %></p>
    <div class="card-body", style="display: flex; justify-content: space-between; margin-top: 10px;">
      <%= link_to 'Back to categories', categories_path, class: "btn btn-warning" %>
      <%= button_to "Destroy this product", @category, method: :delete, class: "btn btn-danger" %>
      <%= link_to 'Edit this category', edit_category_path(@category), class: "btn btn-info" %>
    </div>
  </div>
</div>