config/routes.rb
Rails.application.routes.draw do
  get 'wishlist_product/show'
  get 'wishlist/show'
  resources :carts
  resources :credit_cards
  resources :orders
  resources :billing_addresses
  resources :shipping_addresses
  resources :products
  resources :categories

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#new'

  get "sign_up", to: "users#new"
  get 'log_out', to: 'extra#new'
  get 'accounts', to: 'users#index', as: "users"
  get 'my_account', to: 'users#show'
  get 'products_by_category', to: 'products_by_category#new'
  get 'my_cart', to: 'carts#show'
  get 'wishlist', to: 'wishlist_product#show'
  get 'export_csv_orders', to: 'orders#export_csv'
  post 'carts/add'
  post 'carts/remove'
  post 'carts/update_quantity'
  post 'wishlist_product/add'
  post 'wishlist_product/remove'

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category 
    has_one_attached :image
    has_many :orderables
    has_many :carts, through: :orderables
    has_many :ordered_products
    has_many :wishlist_products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show]
  before_action :check_admin, except: [:show]

  include Pagy::Backend
  # GET /products or /products.json
  def index
    products = Product.includes(:category).all
    products = products.where(category_id: params[:category_id]) if params[:category_id].present?
    products = products.where(brand: params[:brand]) if params[:brand].present?
    products = products.where("name LIKE ? OR description LIKE ?", "%#{params[:search]}%", "%#{params[:description]}%") if params[:search].present?
    products = products.order(:name)
    @pagy, @products = pagy(products)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:id, :name, :brand, :description, :sku, :stock, :price, :category_id, :quantity, :perfumetype, :notes, :image )
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_filter_menu.html.erb
<!-- _filter_menu.html.erb -->
<%= form_tag products_path, method: :get, class: 'form-inline', id: 'orders-form' do %>
  <div class="form-group mb-2">
    <%= label_tag :category_id, 'Filter by category:', class: 'golden-text' %>
    <%= select_tag :category_id, options_for_select(Category.all.pluck(:name, :id), params[:category_id]), {:prompt => 'All', :class => 'select-button'}%>
    
    <%= label_tag :brand, 'Filter by brand:', class: 'golden-text' %>
    <%= select_tag :brand, options_for_select(Product.distinct.pluck(:brand).sort, params[:brand]), {:prompt => 'All', :class => 'select-button'}%>

    <%= text_field_tag(:search, params[:search], class: 'select-button', style: "border-color: transparent; outline-style: solid; outline-color: #C09040; outline-width: thin;") %>

    <%= submit_tag 'Filter', class: 'btn btn-primary mb-2', class: 'gold-button' %>
  </div>

<% end %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="form-outline mb-4">
    <%= f.text_field :name, autofocus: true, required: true, class: "form-control", placeholder: "Name", id: "text-field"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_field :brand, autofocus: true, required: true, class: "form-control", placeholder: "Brand", id: "text-field"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.select(:perfumetype, ['Eau de parfum', 'Eau de toilette'], {:include_blank => "Select type:"} , {:required => true, :class => "form-control", :id => "text-field"}) %>
  </div>
  <br>
  <div class="form-outline mb-4">
    <% if @product.image.attached? then %>
      <%= f.file_field :image %>
    <% else %>
      <%= f.file_field :image, {:required => true, :class => "form-control", :id => "text-field"} %>
    <% end %>
    <%= if @product.image.attached? then image_tag(@product.image, style: "width: 300px; height: 300px;") end%>
  </div>
  <br>
  <div class="form-outline mb-4"> 
    <%= f.text_area :description, required: true, class: "form-control", placeholder: "Description", id: "text-field"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_field :notes, autofocus: true, required: true, class: "form-control", placeholder: "Olfactory notes", id: "text-field"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_field :sku, required: true, class: "form-control", placeholder: "SKU", id: "text-field"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.number_field :stock, min: 0, required: true, class: "form-control", placeholder: "Stock", id: "text-field"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.number_field :price, min: 0, step: 0.01, required: true, class: "form-control", placeholder: "Price in €", id: "text-field"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.number_field :quantity, min: 0, step: 5, required: true, class: "form-control", placeholder: "Quantity in ml", id: "text-field"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.collection_select(:category_id, Category.all, :id, :name, {:include_blank => "Select category:"} , {:required => true, :class => "form-control", :id => "text-field"}) %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit button_text, class: "btn btn-info btn-block mb-4" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
</div>

app/views/products/edit.html.erb
<div class="product">

  <h1 class="font-effect-outline" id="new-product-title">Editing product</h1>

  <%= render "form", button_text: "Update" %>

  <%= link_to "Back to products", products_path, class: "btn btn-warning", id: "back-button" %>
  <%= link_to "Show this product", @product, class: "btn btn-primary", id: "back-button" , style: "float: right;"%> 

</div>

app/views/products/index.html.erb
<div class="container mt-5">
  <h2 class="gold-title">Products</h2>
  <br>
  <%= link_to 'New Product', new_product_path, class: "btn btn-info btn-lg btn-block", id: "new-button" %>
  <br>
  <%= render "filter_menu" %>
  <br>
  <%== pagy_info(@pagy) %>
  <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Brand</th>
          <th scope="col">Description</th>
          <th scope="col">SKU</th>
          <th scope="col">Type</th>
          <th scope="col">Olfactory notes</th>
          <th scope="col">Stock</th>
          <th scope="col">Quantity</th>
          <th scope="col">Category</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.name %></td>
            <td><%= product.brand %></td>
            <td><%= product.description %></td>
            <td><%= product.sku %></td>
            <td><%= product.perfumetype %></td>
            <td><%= product.notes %></td>
            <td><%= product.stock %></td>
            <td><%= product.quantity %> ml</td>
            <td><%= product.category.name %></td>
            <td>
              <%= link_to 'Show', product, class: "btn btn-primary btn-sm", style: "margin:2px;"%> 
              <%= link_to 'Edit', edit_product_path(product), class: "btn btn-success btn-sm", style: "margin:2px;" %> 
              <%= link_to 'Destroy', product, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm", style: "margin:2px;" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination justify-content-center">
      <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1%>
    <div>
</div>

app/views/products/new.html.erb
<div class="product">

  <h1 class="font-effect-outline" id="new-product-title">New product</h1>

  <%= render "form", button_text: "Create" %>

  <%= link_to "Back", products_path, class: "btn btn-warning", id: "back-button" %>
    
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div class="card" style="margin: 30px; padding: 0 20px 0 0; background-color: #FAFAD2; font-family: 'Montserrat', cursive;">
  <div style="display: flex;">
    <%= image_tag(@product.image, height: '600px', style: "float: left; display: inline;")%>
    <div style="overflow: hidden;">
      <div class="card-body">
        <h5 class="card-title" style="opacity: 0.8;"><%= @product.brand %></h5>
        <h3 class="card-title" style="text-shadow: 0.4px 0.4px 0.4px black;"><%= @product.name %></h3>
        <h6 class="card-title" style="opacity: 0.5;"><%= @product.perfumetype %></h6>
        <br>
        <p class="card-text"><%= @product.description %></p>
        <br>
        <h5 class="card-title">Olfactory notes:</h5>
        <p class="card-text"><%= @product.notes %></p>
      </div>
      <div style="display: flex; margin: 15px; text-shadow: 0.4px 0.4px 0.4px black;">
        <h1><%= @product.quantity %> ml</h1>
        <h1 style="margin-left: auto;"><%= @product.price %>€</h1>
      </div>
      <% if user_signed_in? && current_user.role == 'admin' %>
        <div class="card-body" style="display: flex; justify-content: space-between; margin-top: 10px;">
          <%= link_to 'Back', products_path, class: "btn btn-warning" %>
          <%= button_to "Destroy this product", @product, method: :delete, class: "btn btn-danger" %>
          <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-info" %>
        </div>
      <% else %>
        <div class="text-center total font-weight-bold mt-4">
          <% if @product.stock == 0 %>
            <p style="color: red; font-weight: bold;">The product is out of stock!</p>
          <% else %>
            <% if current_user.present? %>
              <div style="display: flex;">
                <% if current_user.wishlist_products.find_by(product_id: @product.id) %> 
                    <%= form_with(url: wishlist_product_remove_path) do |f| %>
                        <%= f.hidden_field :id, value: @product.id %>
                        <%= f.submit "❤️", style: "background-color: transparent; border-color: transparent; font-size: 40px; margin-top: -8px" %>
                    <% end %>
                <% else %>
                    <%= form_with(url: wishlist_product_add_path) do |f| %>
                        <%= f.hidden_field :id, value: @product.id %>
                        <%= f.submit "🤍", style: "background-color: transparent; border-color: transparent; font-size: 40px; margin-top: -8px" %>
                    <% end %>
                <% end %>
                <%= form_with(url: carts_add_path) do |f| %>
                  <%= f.hidden_field :id, value: @product.id %>
                  <%= f.hidden_field :quantity, value: 1 %>
                  <%= f.submit "Add To Cart", class: "gold-button", style: "margin:0px 10px 20px 10px; width: 735px; font-family: 'Kalam', cursive; font-size: 30px;" %>
                <% end %>
                </div>
            <% else %>
              <p class="text-muted mb-0">You need to be logged in to order!</p>
            <% end %>
          <% end %>
        </div>
        <br><br>
        <%= link_to 'BACK', root_path, class: "gold-button-without-underline", style: "margin-left: 90%;"%>
      <% end %>
    </div>
  </div>
</div>